// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhvlrklnuohlvuwpokey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhodmxya2xudW9obHZ1d3Bva2V5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNDA4MDcsImV4cCI6MjA2NzgxNjgwN30.iNTzejaxuAGDDGG_oYQWhzFl08QZDuaFSk-E9tWaKfc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});